name: TF Helper Action
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        cmd: |
            bash -c "tfh pushconfig -message \"Github Action Testing\" -vcs 0 -current-config false"
      env:
        TFH_token: ${{ secrets.TFH_TOKEN }}
        TFH_org: mirrorweb
        TFH_name: mw-tna-dmz-staging
